language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: fXNATFvmxCKP+4FBmVb4R907RFhjAcE7v6OyfqHjQmBWi8Nm+s9rKdtmp4j0gomVATWj0Gn5VjC8o1ZR5YKfZLIuSpCxfOJAAX62WhjFXJIBva6cQedKmBuB5HaAE1JAvA8wC3HQkL5TEa0NVLFJY42U6FVwSX3eFu0lAQX3Sj2eB091tYrfVID59SPx7fdrWGPfP/hwWDO/j6mqPXB10e+WQqWwuET/FTBKXXmt4LfNVdP9OO0WVxGdhCLjSZkIF3Ll2My1TCk2uPqIUEamdF3vwMt1QBzLJvZ2JrKtA9MWLvHdgzjT94C2YVXo4sLkVnBCdHfstwrA50sM+9AyvetUIvIjuhTIkDFZsK/INBUanDuGkUDbhEQU9gu1Pyz+3ZgWV9YiyQY0yw2HAYOfOG582EHfqEoyZ/InPwMIdsFD9LBdzoJJ9mGo1o8m+7PaD5JsIaHXFGU4ZPubTMlkGYrZ7IRZZyQARbft+tdGv08HlNNaMfFAbfs35Cs2/DtEAJfjZAwxiIR8xZ3moQFZEpFgqO5JP64rWAFln6PgzETGahPH+COFkvrQHtXzqpkgoOtWK0NcWDqXB24tparkJ+7btkttMTEhR/bjfYM9FXWkC4HeOFHRZ/5OmrkHrbvEe2VMraNtRQyIjAl1/gjlygS4Yj/3n3Zg5HPAeXsteBA=
  app: Blogful-API-2020
  on:
    repo: Acosta816/Blogful-API-2020
  skip_cleanup: 'true'
